config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'  ### before login
  resources :home do 		### index routes
    collection do
      get "about_us"   ###about_us
      get "contact_us" ###Contact_us
      get "cashtelex_exchange" ###services1
      get "cashtelex_go" ###services2
      get "cashtelex_coin" ###services3
      get "cashtelex_real_estate" ###services1
      get "cashtelex_gold" ###services1
    end
  end

  devise_for :admins, :controllers => { :registrations => :registrations }

  namespace :admins do
    resources :dashboards
    resources :abouts
    resources :terms
    resources :services do
      resources :service_providers do 
        collection do
          post :get_states 
        end
      end
    end
  end
end

app/models/service_provider.rb
class ServiceProvider < ApplicationRecord
  belongs_to :service

  validates_presence_of :name, :quantity, :price_in_gram, :price_in_btc, :price_in_ctlx
  validates_uniqueness_of :name
end

app/controllers/admins/service_providers_controller.rb
class Admins::ServiceProvidersController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_service
  before_action :get_service_provider, except: :index
  skip_before_action :verify_authenticity_token, only: :get_states

  layout "admin"

  def index
    @service_providers = @service.service_providers.order(id: :desc)
  end

  def new; end 

  def create
    @service_provider.assign_attributes(service_provider_attributes)
    if @service_provider.save
      redirect_to action: :index
    else
      render action: :new
    end
  end 

  def show; end 

  def edit; end 
    
  def update
    if @service_provider.update_attributes(service_provider_attributes)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    if @service_provider.destroy
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  # post: /service/:service_id/service_providers/get_states
  def get_states
    country_code = params[:country_code] || "US"
    @states = ISO3166::Country[country_code].states.map { |state| [state[1]['name'], state[0]] }
    @selected_state = params[:state]
  end

  private

  def get_service
    @service = Service.find(params[:service_id])
  end

  def get_service_provider
    if params[:id].present?
      @service_provider = @service.service_providers.find(params[:id])
    else
      @service_provider = @service.service_providers.build
    end
  end

  def service_provider_attributes
    params.require(:service_provider).permit(:name, :country, :state, :city, :zipcode, :address, :description, :quantity, :price_in_gram, :price_in_btc, :price_in_ctlx)
  end
end

app/helpers/admins/service_providers_helper.rb
module Admins::ServiceProvidersHelper
end

app/views/admins/service_providers/_form.html.erb
<%= form_for([:admins, @service, @service_provider], class: "box-type1  notify") do |f|  %>
<%= render "devise/shared/error_messages", resource: @service_provider %>
<div class="row">
   <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
      <div class="form-label">
         <p class="col-grey"> Shop Name </p>
      </div>
      <div class="form-field1 m-b-20">
         <%= f.text_field :name, class: "form-control" %>
      </div>
   </div>
   <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
      <div class="form-label">
         <p class="col-grey"> Country </p>
      </div>
      <div class="form-field1 m-b-20">
        <%= f.country_select :country, ['United States', 'Canada', 'United Kingdom', 'India'] %>
      </div>
   </div>
   <div class="col-md-6 col-lg-6">
      <div class="form-label">
         <p class="col-grey"> State  </p>
      </div>
      <div class="form-field1 m-b-20">
         <div class="form-field1 m-b-20" id="states" >
            <!-- STATES WILL BE DYNAMICALLY APPENDED BY THE AJAX -->
         </div>
      </div>
   </div>
   <div class="col-md-6 col-lg-6">
      <div class="form-label">
         <p class="col-grey"> City </p>
      </div>
      <div class="form-field1 m-b-20" id="citites">
        <%= f.text_field :city, class: "form-group" %>
      </div>
   </div>
   <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6"    style="clear:both;">
      <div class="form-label">
         <p class="col-grey"> Quantity </p>
      </div>
      <div class="form-field1 m-b-20">
         <%= f.number_field :quantity, class: "form-group" %>
      </div>
   </div>
   <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
      <div class="rate-used-sec">
         <div class="rate-inner-used-sec">
            <div class="form-label">
               <p class="col-grey"> Rate Per Gram in USD </p>
            </div>
            <div class="form-field1 m-b-20">
               <%= f.number_field :price_in_gram, min: 1, step: 0.5, class: "form-group" %>
            </div>
         </div>
         <div class="rate-inner-used-sec  rate-btc">
            <div class="form-label">
               <p class="col-grey"> Rate in BTC </p>
            </div>
            <div class="form-field1 m-b-20">
               <%= f.number_field :price_in_btc, min: 1, step: 0.5, class: "form-group" %>
            </div>
         </div>
         <div class="rate-inner-used-sec  rate-ctlx">
            <div class="form-label">
               <p class="col-grey"> Rate in CTLX </p>
            </div>
            <div class="form-field1 m-b-20">
               <%= f.number_field :price_in_ctlx, min: 1, step: 0.5, class: "form-group" %>
            </div>
         </div>
      </div>
   </div>
   <!-- <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
      <div class="add-images">
          <div class="rate-header-sec">
          <div class="form-label">
              <p class="col-grey"> Add Images </p>
          </div>
          </div>
      <div class="add-images-sec">
          <div class="uploaded-sec-img">
              <div class="row">
                  <div class="col-md-4 preview previwe-c text-center  img-hh">
                      <div class="inner-pro">
                      <div class="preview-box">
                          <%= image_tag("img-2/gallery-1.png") %>
                      </div>
                      <div class="browse-button delete-medical-report" data-id="97">
                          <i class="fas fa-times"></i>
                      </div>
                      </div>
                  </div>
                  <div class="col-md-4 preview previwe-c text-center  img-hh">
                      <div class="inner-pro">
                      <div class="preview-box">
                          <%= image_tag("img-2/gallery-1.png") %>
                      </div>
                      <div class="browse-button delete-medical-report" data-id="97">
                          <i class="fas fa-times"></i>
                      </div>
                      </div>
                  </div>
                  <div class="col-md-4 preview previwe-c text-center upload-img-hhc">
                      <div class="inner-pro">
                      <div class="browse-button">
                          <i class="fa fa-plus"></i>
                          <input class="browse-input" type="file" required="" name="UploadedFile" id="userImage" accept="image/jpeg,image/png,application/pdf">
                      </div>
                      <div class="preview-box">Browse Image</div>
                      </div>
                  </div>
              </div>
          </div>
      </div> 
      </div>
      </div> -->
   <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
      <div class="form-label">
         <p class="col-grey"> Zipcode </p>
      </div>
      <div class="form-field1 m-b-20">
         <%= f.number_field :zipcode, class: "form-group" %>
      </div>
   </div>
   <div class="col-md-6 col-lg-6">
      <div class="form-label">
         <p class="col-grey"> Address </p>
      </div>
      <div class="form-field1 m-b-20">
         <%= f.text_field :address, class: "form-group" %>
      </div>
   </div>
   <div class="col-md-12">
      <div class="form-label">
         <p class="col-grey"> Description </p>
      </div>
      <div class="form-field1 m-b-20">
         <%= f.text_area :description, class: "form-control" %>
      </div>
   </div>
   <div class="col-md-12">
      <%= f.submit "Save Gold", class: " save-c btn edit-gold" %>
   </div>
</div>
<% end %>

<%= content_for :javascript do %>
  <script>
    var countrySelectBox = document.querySelector("#service_provider_country");
    var service_id = "<%= params[:service_id] %>";
    var url = "/admins/services/"+service_id+"/service_providers/get_states"
    var state = "<%= @service_provider.state %>"
    
    hit_ajax(countrySelectBox.value, state); // load states on page load
    
    // load states when the country changess
    countrySelectBox.addEventListener("change", (event) => {
      hit_ajax(event.target.value);
    });

    function hit_ajax(country_code = "US", state = "") {
      $.ajax({
        url: url,
        method: 'POST',
        data: { country_code: country_code, state: state },
        success: function(data) {
            console.log('success')
        },
        error: function() {
            console.log('failure')
        }
      });
    }
  </script>
<% end %>

app/views/admins/service_providers/edit.html.erb
<section class="all-dashboard instructor-sec">
   <div class="dashboard-wrapper edit-cahtelex">
      <div class="row m-b-20">
         <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="page-title">
               <h3 class="col-black"> Cashtelex Gold </h3>
            </div>
         </div>
      </div>
      <div class="block-element">
        <%= render "form" %>
      </div>
   </div>
</section>

app/views/admins/service_providers/get_states.js.erb
$('#states').html("<%=j select(:service_provider, :state, @states, selected: @selected_state) %>")

app/views/admins/service_providers/index.html.erb
<section class="all-dashboard instructor-sec user-html-c">
   <div class="dashboard-wrapper  cashtolex-gold-sec">
      <div class="block-element">
         <div class="row m-b-20">
            <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
               <div class="page-title">
                  <h3 class="col-black"> Service Provider </h3>
               </div>
            </div>
            <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12 ">
               <div class="right-side-c">
                  <div class="date-sec custom-c34">
                     <div class="serach-bar">
                        <input type="text" class="form-control" placeholder="Search Member">
                        <span><i class="fa fa-search"></i></span>
                     </div>
                     <span class="add-new">  Add New  </span>
                    <%= link_to new_admins_service_service_provider_path(@service) do %>
                      <span class="cal-icon icon-d  custom-c2">
                        <%= image_tag("img-2/add-icon.png") %>
                      </span>
                    <% end %>  
                  </div>
               </div>
            </div>
         </div>
         <div class="block-element dash-div">
            <div class="row">
               <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12">
                  <div class="dashboard-box box-type1">
                     <div class="dash-title first-div">
                        <h4><%= service_providers_stats("gold") %></h4>
                        <p class="col-grey"> Total Gold </p>
                     </div>
                  </div>
               </div>
               <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12">
                  <div class="dashboard-box box-type1">
                     <div class="dash-title sec-div">
                        <h4><%= service_providers_stats("us_price") %></h4>
                        <p class="col-grey"> Total USD Price </p>
                     </div>
                  </div>
               </div>
               <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12">
                  <div class="dashboard-box box-type1">
                     <div class="dash-title third-div">
                        <h4><%= service_providers_stats("btc_price") %></h4>
                        <p class="col-grey"> Total BTC Price</p>
                     </div>
                  </div>
               </div>
               <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12">
                  <div class="dashboard-box box-type1">
                     <div class="dash-title four-div">
                        <h4><%= service_providers_stats("ctlx_price") %></h4>
                        <p class="col-grey"> Total CTLX Price </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="block-element gold-headings">
            <div class="row">
               <h3>Total Gold Shapes</h3>
            </div>
         </div>
         <div class="row">
            <table class="table-type1">
               <tbody>
                  <tr>
                     <th class="col-black"> Sr.No. </th>
                     <th class="col-black"> Photo </th>
                     <th class="col-black">Country </th>
                     <th class="col-black"> Grams Quantity </th>
                     <th class="col-black"> Zipcode </th>
                     <th class="col-black"> USD Rate Per Gram  </th>
                     <th class="col-black"> In Btc </th>
                     <th class="col-black"> In CTLX </th>
                     <th class="col-black"> Actions </th>
                  </tr>
                  <% @service_providers.each do |provider| %>
                    <tr>
                        <td><%= provider.id %></td>
                        <td class="photo-c"> <%= image_tag("user-pic.png") %>
                        <td><%= provider.country %></td>
                        <td><%= provider.quantity %> Grams</td>
                        <td><%= provider.zipcode %></td>
                        <td> $<%= provider.price_in_gram %> </td>
                        <td> <%= provider.price_in_btc %></td>
                        <td> <%= provider.price_in_ctlx %></td>
                        <td class=" actions-btn-c">
                          <%= link_to admins_service_service_provider_path(@service, provider), class: "edit-btn-f" do %>
                            <%= image_tag("img-2/eye.png") %>
                          <% end %>

                          <%= link_to edit_admins_service_service_provider_path(@service, provider), class: "edit-btn-f" do %>
                            <%= image_tag("img-2/content.png") %>
                          <% end %>

                          <%= link_to admins_service_service_provider_path(@service, provider), class: "edit-btn-f", method: :delete, data: { confirm: "Are you sure?" } do %>
                            <%= image_tag("img-2/cross.png") %>
                          <% end %>
                        </td>
                    </tr>
                  <% end %>   
               </tbody>
            </table>
         </div>
      </div>
   </div>
</section>

app/views/admins/service_providers/new.html.erb
<section class="all-dashboard instructor-sec">
   <div class="dashboard-wrapper edit-cahtelex">
      <div class="row m-b-20">
         <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="page-title">
               <h3 class="col-black"> Cashtelex Gold </h3>
            </div>
         </div>
      </div>
      <div class="block-element">
        <%= render "form" %>
      </div>
   </div>
</section>