config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'  ### before login
  resources :home do 		### index routes
    collection do
      get "about_us"   ###about_us
      get "contact_us" ###Contact_us
      get "cashtelex_exchange" ###services1
      get "cashtelex_go" ###services2
      get "cashtelex_coin" ###services3
      get "cashtelex_real_estate" ###services1
      get "cashtelex_gold" ###services1
    end
  end

  devise_for :admins, :controllers => { :registrations => :registrations }

  namespace :admins do
    resources :dashboards
    resources :abouts
    resources :terms
    resources :services do
      resources :service_providers do 
        collection do
          post :get_states 
        end
      end
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  layout "admin"
  before_action :authenticate_admin! , except: [:new, :create]
  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to root_path, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to tickets_path, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
       params.require(:ticket).permit(:name, :email, :message, :status)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<section class="all-dashboard instructor-sec user-html-c">
   <div class="dashboard-wrapper  cashtolex-gold-sec">
      <div class="block-element">
         <div class="row m-b-20">
            <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
               <div class="page-title">
                  <h3 class="col-black"> Customer Support </h3>
               </div>
            </div>
            <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12 ">
               <div class="right-side-c">
                  <div class="date-sec custom-c34">
                     <div class="serach-bar">
                        <input type="text" class="form-control" placeholder="Search Member">
                        <span><i class="fa fa-search"></i></span>
                     </div>
                    
                  </div>
               </div>
            </div>
         </div>
        
         <div class="block-element gold-headings">
            <div class="row">
               <h3>Total Tickets</h3>
            </div>
         </div>
         <div class="row">
            <table class="table-type1">
               <tbody>
                  <tr>
                     <th class="col-black"> Sr.No. </th>
                     <th class="col-black"> Name </th>
                     <th class="col-black"> Email </th>
                     <th class="col-black"> Message </th>
                     <th class="col-black"> Status </th>
                     <th class="col-black"> Actions </th>
                  </tr>
                  <% @tickets.each do |ticket| %>
                    <tr>
                        <td><%= ticket.id %></td>
                        <td><%= ticket.name %></td>
                        <td><%= ticket.email %></td>
                        <td><%= ticket.message %></td>
                        <td><%= ticket.status %></td>
                        
                        <td class=" actions-btn-c">
                          <%= link_to ticket, class: "edit-btn-f" do %>
                            <%= image_tag("img-2/eye.png") %>
                          <% end %>

                          <%= link_to ticket, class: "edit-btn-f", method: :delete, data: { confirm: "Are you sure?" } do %>
                            <%= image_tag("img-2/cross.png") %>
                          <% end %>
                        </td>
                    </tr>
                  <% end %>   
               </tbody>
            </table>
         </div>
      </div>
   </div>
</section>
 

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<section class="all-dashboard instructor-sec user-html-c">
   <div class="dashboard-wrapper  cashtolex-gold-sec">
      <div class="block-element">
         <div class="row m-b-20">
            <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
               <div class="page-title">
                  <h3 class="col-black"> Customer Support </h3>
               </div>
            </div>
            
         </div>
        
         <div class="row">
              <div class="custom-s">
                     <div class="row">
                        <div class="col-md-12"> 

                     <div class="customer-upper-sec">
                        
                        <div class="customer-text-right">
                          <div class="form-label">
                                 <p class="col-grey"> Customer </p>
                              </div>
                            <h3><%= @ticket.name %></h3> 
                            <br> 
                              <div class="form-label">
                                 <p class="col-grey"> Email </p>
                              </div>
                            <h3><%= @ticket.email %> </h3>   
                        </div>

                     </div>                   
                     </div>


                       <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 message-d">
                              <div class="form-label">
                                 <p class="col-grey"> Message </p>
                              </div>
                              <div class="form-field1 m-b-20">
                                 <%= @ticket.message %>
                              </div>
                           </div> 
                        <div class="row btn-d text-right">
                           <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                              <%= link_to "Mark As Resolved", ticket_path(@ticket, ticket: {status: 'closed'}), class: 'save-c', :method=> :put    %>
                            </div>
                        </div>  
                  </div>

                    
                  </div>
         </div>
      </div>
   </div>
</section>
 