config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'  ### before login
  resources :home do 		### index routes
    collection do
      get "about_us"   ###about_us
      get "contact_us" ###Contact_us
      get "cashtelex_exchange" ###services1
      get "cashtelex_go" ###services2
      get "cashtelex_coin" ###services3
      get "cashtelex_real_estate" ###services1
      get "cashtelex_gold" ###services1
    end
  end

  devise_for :admins, :controllers => { :registrations => :registrations }

  namespace :admins do
    resources :dashboards
    resources :abouts
    resources :terms
    resources :services do
      resources :service_providers do 
        collection do
          post :get_states 
        end
      end
    end
  end
end

app/views/layouts/partials/_header.html.erb
<div class="dashboard-menu">
  <button class="navbar-toggler navbar-toggler bars-icons align-self-center" type="button" data-toggle="minimize">
    <!-- <i class="fa fa-bars"></i> -->
  </button>
  <%# if controller_name == "registrations" %>
    <!-- <label class="switch">
      <span class="online-text">Online</span>
      <input type="checkbox" checked>
      <span class="slider round"></span>
    </label> -->
  <%# end %>
  <div class="notification-dropdown">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= image_tag("img-1/notification.png", alt: "bell-icon") %><span class="counter1"> 3 </span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li><a href="#">Profile</a></li>
        <li><a href="#">Settings</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Log Out</a></li>
      </ul>
    </div>
  </div>
  <div class="user-dropdown">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <b><%= current_admin %></b><span> Super Admin </span>
        <%= image_tag("user-pic.png") %>
        <i class="fa fa-caret-down"> </i>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li><a href="/admins/edit">Settings</a></li>
        <li><a href="/admins/edit">Change Password</a></li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to destroy_admin_session_path, method: :delete do %>
            Log Out
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/partials/_service_header.html.erb
<header class="services-page-header">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light">
               <a class="navbar-brand" href="#">
               <img src="/assets/logo-1.png" alt="">
               </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav ml-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="/home">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="/home/about_us">About Us</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="/home/contact_us">Contact Us</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="#">Cashtelex Tower</a>
                     </li>                             
                     <li class="nav-item">
                        <a class="nav-link" href="#">Cashtelex Gold</a>
                     </li>
                     <% if current_admin.present?%>
                        <li class="nav-item profile-d">
                           <a class="nav-link" href="#"><img src="/assets/Services/profile.png">
                           <span>Hi, Stephen</span>
                           </a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="#"><img src="/assets/Services/logout-icon.png"></a>
                        </li>
                     <% end %>
                  </ul>
               </div>
            </nav>
         </div>
      </div>
   </div>
</header>

app/views/layouts/partials/_sidebar.html.erb
<section class="sidebar-left">
  <div class="sidebar-custom">
    <div class="sidebar-logo">
      <a href="/home"> <%= image_tag("img-1/logo.png") %> </a>
      <button class="menu-hamburger"><%= image_tag("hamburger.png") %> </button>
    </div>
    <div class="sidebar-menu">
      <div class="menu-item">
        <a href="<%= admins_dashboards_path %>" class="<%= current_class_on_tab("dashboards") %>"><%= image_tag("img-1/home.png") %> Dashboard </a>
      </div>
      <div class="menu-item  collapse-d2">
        <a href="javascript:void(0);" id="service_parent_tab" data-toggle="collapse" data-target="#demo">
          <%= image_tag("img-2/store.png", class: "active-c") %>
          Services  
          <span> 
            <i class="fa fa-angle-right" aria-hidden="true"></i>
          </span>
        </a>
        <div id="demo" class="collapse">
            <%  Service.all.each do |service| %>
              <%= link_to edit_admins_service_path(service), class: current_class_on_tab("services", service.id) do %>
                <%= image_tag service_image_path(service.title), class: "active-c" %> <%= service.title %>
              <% end %>
            <% end %>
        </div>
      </div>
      <div class="menu-item">
        <%= link_to admins_service_service_providers_path(gold_service.id), class: current_class_on_tab("service_providers") do %>
          <%= image_tag service_image_path(gold_service.title), class: "active-c" %> <%= gold_service.title %>
        <% end %>
      </div>
      <div class="menu-item">
        <a href="<%= edit_admins_about_path(About.first) %>" class="<%= current_class_on_tab("abouts") %>"><%= image_tag("img-1/document.png") %> About  Us  </a>
      </div>
      <div class="menu-item">
        <a href="<%= edit_admins_term_path(Term.first) %>" class="<%= current_class_on_tab("terms") %>"><%= image_tag("img-1/document.png") %> Terms and Condition</a>
      </div>
      <div class="menu-item">
        <a href="/tickets" class="<%= current_class_on_tab("tickets") %>"><%= image_tag("img-1/document.png") %> Support Tickets </a>
      </div>
      <div class="menu-item">
        <a href="<%= edit_admin_registration_path %>" class="<%= current_class_on_tab("registrations") %>"><%= image_tag("img-1/setting-spanner.png") %> Setting </a>
      </div>
      <!-- Logout functionality -->
      <div class="menu-item">
        <%= link_to destroy_admin_session_path, method: :delete do %>
          <%= image_tag("img-1/logout.png") %> Logout
        <% end %>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  jQuery(".navbar-toggler").click(function(){
    alert("hi")
  jQuery(".sidebar-left").toggleClass("hide_sidebar");
});
</script>